services:
  rhizal:
    image: node:23
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./config/signal:/home/.local/share/signal-cli
    command: sh -c "yarn install && yarn build && yarn dev"
    environment:
      - HASURA_GRAPHQL_URL=${HASURA_GRAPHQL_URL}
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}
      - ACCOUNT_PHONE=${ACCOUNT_PHONE}
    depends_on:
      - signal-cli
    networks:
      - app-network

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    volumes:
      - ./config/signal:/home/.local/share/signal-cli
    ports:
      - "8080:8080"
    environment:
      - MODE=json-rpc
    networks:
      - app-network

networks:
  app-network:
    driver: bridge