version: '0.2'

services:
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "yarn install && sleep 5 && yarn dev"
    environment:
      - HASURA_GRAPHQL_URL=${HASURA_GRAPHQL_URL}
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}
      - ACCOUNT_PHONE=${ACCOUNT_PHONE}
    depends_on:
      - signal-cli
    volumes:
      - ./config/signal:/home/.local/share/signal-cli
    networks:
      - app-network

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    volumes:
      - ./config/signal:/home/.local/share/signal-cli
    environment:
      - MODE=json-rpc
    networks:
      - app-network

networks:
  app-network:
    driver: bridge