services:
  rhizal:
    image: node:23
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./config/signal:/home/.local/share/signal-cli
    command: sh -c "yarn install && yarn build && yarn start"
    environment:
      - GRAPHQL_URL=${GRAPHQL_URL}
      - GRAPHQL_ADMIN_SECRET=${GRAPHQL_ADMIN_SECRET}
      - GRAPHQL_AUTH_HEADER=${GRAPHQL_AUTH_HEADER}
      - ACCOUNT_PHONE=${ACCOUNT_PHONE}
    depends_on:
      - signal-cli
    networks:
      - app-network

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    volumes:
      - ./config/signal:/home/.local/share/signal-cli
    environment:
      - MODE=json-rpc
    networks:
      - app-network

networks:
  app-network:
    driver: bridge